spring.application.name=aml
# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/aml?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=testing123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.security=DEBUG

jwt.expiration=200000